spring:
  application:
    name: openai-communication
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-5-nano
          temperature: 1.0
server:
  port: 8081